# name: Deploy
# on:
#   push:
#     branches:
#       - main

name: Open new issue
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [16.x]
    permissions:
      contents: write
      issues: write
    steps:
      # - run: |
      #     gh issue --repo ${{ github.repository }} \
      #       create --title "Issue title" --body "Issue body"
      #   env:
      #     GH_TOKEN: ${{ secrets.TOKEN }}

      - uses: actions/checkout@master
        with:
          node-version: ${{ matrix.node-version }}    
    

      # - name: Access for gitmodules
      #   env:
      #     SSH_KEY_GITMODULES: ${{secrets.PRI_SSH_KEY}}
      #   run: |
      #     mkdir $HOME/.ssh
      #     echo "$SSH_KEY_GITMODULES" > $HOME/.ssh/id_rsa
      #     chmod 400 $HOME/.ssh/id_rsa
      #     cat $HOME/.ssh/id_rsa
          

      - name: Checkout code
        uses: actions/checkout@master
      - name: Linux 
        run: ls -al
      - run: touch test
      - run: echo "Still testing12" > test
      - run: git config --global user.email "er.vishalkumargupta@gmail.com"
      - run: git config --global user.name "0xvishal" 
      #- run: git credential-osxkeychain erase host=github.com protocol=https
      #- run: git remote set-url origin https://USERNAME:TOKEN@github.com/USERNAME/REPO.git 
      #- run: git remote set-url origin https://0xvishal:${{ secrets.TOKEN }}@github.com/0xvishal/status.git

      - run: git add .
      - run: git commit -m "add test file"
      #- run: git remote add origin https://${{ secrets.TOKEN }}@github.com/0xvishal/status
      - run: git push origin main
      
      # - name: Checkout Target Repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 0xvishal/status
      #     path: infra/helm
      #     # token: ${{ secrets.TOKEN }}

      # - name: Update Image Version in the related HelmChart values.yaml
      #   uses: OpsVerseIO/image-updater-action@0.1.0
      #   with:
      #     valueFile: 'infra/helm/qa.values.yaml'
      #     propertyPath: 'deployment.containers.version'
      #     value: 'v1.2.3'
      #     branch: main/v1.2.3
      #     targetBranch: main
      #     createPR: true
      #     message: 'Update Image Version to v1.2.3'

      # - name: Update Image Version in the related HelmChart values.yaml
      #   uses: OpsVerseIO/image-updater-action@0.1.0
      #   with:
      #     valueFile: 'infra/helm/qa.values.yaml'
      #     propertyPath: 'deployment.containers.version'
      #     value: 'v1.2.3'
      #     branch: main/v1.2.3
      #     targetBranch: main
      #     masterBranchName: main
      #     createPR: false
      #     message: 'Update Image Version to 1.2.3' 

      # - name: Update values.yaml
      #   run: pwd
      # - run: ls infra/helm  



      # - name: Update values.yaml
      #   run: |      
      #     # cd infra/helm
      #     # cat infra/helm/qa.values.yaml
      #     # ls -al
      #     # sed -i 's|version:.*|version: 'v1.2.3'|' infra/helm/qa.values.yaml 
      #     touch test
      #     echo "this is test file " > test
      #     # git config --global user.name 'GitHub Actions'
      #     # git config --global user.email 'actions@github.com'
      #     # git config --global user.email "er.vishalkumargupta@gmail.com"
      #     # git config --global user.name "0xvishal"
      #     git add .
      #     git commit -m "add file"
      #     # git remote set-url origin https://0xvishal:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
      #     git push 
      #     # git add qa.values.yaml
      #     # git commit -m "Update qa.values.yaml"
      #     # git push



          

