name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [16.x]
    steps:
      - uses: actions/checkout@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: 0xvishal/status
          path: infra/helm
          token: ${{ secrets.TOKEN }}

      # - name: Update Image Version in the related HelmChart values.yaml
      #   uses: OpsVerseIO/image-updater-action@0.1.0
      #   with:
      #     valueFile: 'infra/helm/qa.values.yaml'
      #     propertyPath: 'deployment.containers.version'
      #     value: 'v1.2.3'
      #     branch: main/v1.2.3
      #     targetBranch: main
      #     createPR: true
      #     message: 'Update Image Version to v1.2.3'

      - name: Update Image Version in the related HelmChart values.yaml
        uses: OpsVerseIO/image-updater-action@0.1.0
        with:
          valueFile: 'infra/helm/qa.values.yaml'
          propertyPath: 'deployment.containers.version'
          value: 'v1.2.3'
          branch: main/v1.2.3
          targetBranch: main
          createPR: true
          message: 'Update Image Version to 1.2.3' 

